dist: precise
git:
  depth: 1
language: ruby
cache:
  apt: true
  directories:
    - vendor/bundle
    - $HOME/.cache/pip
sudo: required
addons:
  apt:
    packages:
      - haveged
python:
  - 2.7
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-19mode
  - jruby-head
gemfile:
  - Gemfile
  - Gemfile.master
before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - gem update --system
  - gem --version
  - gem install bundler
  - sudo apt-get update -qq
install:
  - wget -O phantomjs-2.1.1-linux-x86_64.tar.bz2 https://github.com/pepijnve/asciidoctor-diagram-build/blob/master/linux/x86_64/phantomjs-2.1.1-linux-x86_64.tar.bz2?raw=true
  - tar jxf phantomjs-2.1.1-linux-x86_64.tar.bz2
  - export PHANTOMJS_2=$PWD/phantomjs-2.1.1-linux-x86_64/bin/phantomjs
  - wget -O phantomjs-1.9.8-linux-x86_64.tar.bz2 https://github.com/pepijnve/asciidoctor-diagram-build/blob/master/linux/x86_64/phantomjs-1.9.8-linux-x86_64.tar.bz2?raw=true
  - tar jxf phantomjs-1.9.8-linux-x86_64.tar.bz2
  - export PHANTOMJS_19=$PWD/phantomjs-1.9.8-linux-x86_64/bin/phantomjs
  - sudo apt-get install -qq graphviz
  - sudo apt-get install -qq python-gtk2 python-cairo
  - sudo apt-get install -qq ttf-dejavu
  - export BLOCKDIAG_FONTPATH=/usr/share/fonts/truetype/ttf-dejavu/DejaVuSans.ttf
  - pip install --user "blockdiag[pdf]" "actdiag[pdf]" "seqdiag[pdf]" "nwdiag[pdf]"
  - pip install --user shaape
  - bundle install --path vendor/bundle --jobs=3 --retry=3
  - npm install -g mermaid
  - npm install -g wavedrom-cli
  - sudo apt-get install -qq imagemagick
# Install umlet
  - curl -s -O http://www.umlet.com/umlet_14_2/umlet-standalone-14.2.zip
  - unzip -qq umlet-standalone-14.2.zip
  - cp Umlet/umlet.sh Umlet/umlet
  - chmod +x Umlet/umlet
  - export PATH=$PATH:$PWD/Umlet/
